export const ADD_BLOOD_SUGAR_RECORD = "ADD_BLOOD_SUGAR_RECORD";
export const RECORD_DATA_LOADED = "RECORD_DATA_LOADED";
export const PROFILE_DATA_LOADED = "PROFILE_DATA_LOADED";
export const USER_LOGIN = "USER_LOGIN";
export const EDIT_DIABETES_PROFILE = "EDIT_DIABETES_PROFILE";